Add warn_[cpus|gpus]_not_multiple_of and logic
glotzerlab/row pull request #15
Opened 2024-06-13 17:16 UTC by janbridley

## Description

Add additional keys to warn users when their job is of an unexpected size. Update Frontier default configuration to use the new keys.

## Motivation and context

On clusters with no shared partition, some jobs need to request more resources than strictly required in order for the allocation to be granted. Adding a warning configuration option will give users feedback on underutilized jobs without preventing these partial jobs from running.

Note that warnings are returned *after* the job submission is confirmed.

## How has this been tested?

Existing tests have been updated to use the new keys. Due to the nature of the warnings, it is nontrivial to add new tests. This can be addressed in a later PR.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/row/blob/trunk/doc/src/developers/contributing.md).
- [x] I agree with the terms of the [**Row Contributor Agreement**](https://github.com/glotzerlab/row/blob/trunk/ContributorAgreement.md).
- [x] My name is on the list of contributors (`doc/src/contributors.md`) in the pull request source branch.
- [x] I have added a change log entry to `doc/src/release-notes.md`.

2024-06-13 17:30 UTC, janbridley commented
If it would be beneficial to add new tests, please let me know! I cannot seem to build Row on Frontier so the current code is untested in practice.

2024-06-13 17:33 UTC, janbridley commented on doc/src/release-notes.md
> +*Changed*
```suggestion
*Changed:*
```

2024-06-17 17:05 UTC, joaander requested changes
Thanks! There are some things to do before merging:

- [ ] Name the keys appropriately (see the comment below).
- [ ] Document the new keys in `cluster.md`.
- [ ] Use the new keys in the `andes` cluster.

I've looked into moving up where the warning is issued. This is difficult because we cannot warn until we know the partition. If we rewrote the code to call `find_partition` before `submit`, then we would either end up calling `find_partition` twice (and seeing the warning twice), or making some big refactors to the code that require a persistent scheduler object. For example, we could implement a `prepare` method that must be called on all actions/directories before `submit`. This isn't a very clean API.

Either case would cause a large change in behavior. Currently `submit` will submit the first `N-1` jobs successfully when the N'th cannot find a partition. If we check all the partitions first, then `submit` would submit 0 jobs in this case.

How much of a problem is it that the warning comes after the confirmation?

2024-06-17 17:05 UTC, joaander commented on doc/src/release-notes.md
> +* `warn_[cpus|gpus]_multiple_of` key for *clusters.toml*
These keys are misnamed. The action is not to warn when it *is* a multiple of, but when it *is not*.

```suggestion
* `recommend_[cpus|gpus]_multiple_of` key for *clusters.toml*
```
The word `recommend` matches the word in the warning. `prefer` would also work.

2024-06-17 17:30 UTC, janbridley commented on doc/src/release-notes.md
> +* `warn_[cpus|gpus]_multiple_of` key for *clusters.toml*
Would warn_*_not_multiple_of be clearer? This is a nitpick at this point, but we may as well

2024-06-17 17:33 UTC, janbridley commented
> I've looked into moving up where the warning is issued. This is difficult because we cannot warn until we know the partition. If we rewrote the code to call `find_partition` before `submit`, then we would either end up calling `find_partition` twice (and seeing the warning twice), or making some big refactors to the code that require a persistent scheduler object. For example, we could implement a `prepare` method that must be called on all actions/directories before `submit`. This isn't a very clean API.
> 
> Either case would cause a large change in behavior. Currently `submit` will submit the first `N-1` jobs successfully when the N'th cannot find a partition. If we check all the partitions first, then `submit` would submit 0 jobs in this case.
> 
> How much of a problem is it that the warning comes after the confirmation?

I think it is probably OK - while less than optimal, I think the downsides of addressing the issue outweigh the minor upside. Most clusters have a shared partition, and users on Frontier/Andes (those who would see this warning) are likely to have significant experience anyway.

2024-06-18 12:08 UTC, joaander commented on doc/src/release-notes.md
> +* `warn_[cpus|gpus]_multiple_of` key for *clusters.toml*
Good point. `warn_*_not` is more explicit about what it does. "Prefer" is vague and seems to indicate that **row** might take some sort of additional action based on this preference.

2024-06-18 17:59 UTC, joaander approved these changes
Thanks!

2024-06-18 17:59 UTC, joaander commented on doc/src/release-notes.md
> +## 0.1.4 (2024-06-13)
```suggestion
## 0.2.0 (not yet released)
```

2024-06-18 18:03 UTC, merged